### ISSUE TITLE
The Blood Stained Journal seems to be in every Creative tab.

### ISSUE THREAD

**Issue by LEWeee** [DavidM1A2/AfraidOfTheDark#1]
I'm not really sure if this is a bug or what, but it is really annoying. Basically the Blood Stained Journal seems to be in (almost) every creative inventory tab. There are a few exceptions like the mods made by Vazkii. The Blood Stained Journal seems to just be there rather than replace any existing blocks or items.

A few images it it will help:
https://imgur.com/a/w8c0A3g
I tried getting as many of them as possible, but of course, it's not like I can capture all of the instances of this happening in my modpack.

**Comment by DavidM1A2** [comment]
Well, I haven't actually seen this before but I also haven't worked with other mods together with Afraid of the Dark either. I'll take a look at this, it's definitely a bug, but I'm not sure if it's something I did incorrectly or if it's a forge bug. Thanks for reporting it though!

**Comment by DavidM1A2** [comment]
Update: I recreated the issue, I'll see if I can fix it.

**Comment by DavidM1A2** [comment]
Was an easy fix -- The fix will be released whenever I put up a new version. I will probably wait a little bit to see if any other bugs get discovered.
