### ISSUE TITLE
Lost everything after leaving the end

### ISSUE THREAD

**Issue by LuigiTP** [DavidM1A2/AfraidOfTheDark#10]
went to the end and when i came back it started saying i didnt know how to use certain items i was using before
i had unlocked everything and after i came to the overworld it reset all the progress
including the void chest 
idk what happened im in 1.16.5

**Comment by LuigiTP** [comment]
So it turns out it didnt erase it it basically made a new profile for us we discovered this becasue the chest from one of us still had stuff but for the owner it was empty
idk where the files are that save this type of thing but if you could tell me so i can fix it ill be very happy

**Comment by LuigiTP** [comment]
well nvm i rmemeber the mod simply creates a space in the same dimension so  i found my old cords in void chest and got my stuff back
still weird tho

**Comment by DavidM1A2** [comment]
Hey LuigiTP, That's definitely a bug. I'll try to reproduce it, and if I can I'll try to fix it

**Comment by DavidM1A2** [comment]
Yup found the bug. Looks like some vanilla logic got changed between 1.14 and 1.16 that changed how going through the end portal resets your player. It's an easy fix, but I'm sorry that it reset all your progress :(

**Comment by LuigiTP** [comment]
ngl was not expecting a reply so soon but thanks
only bummer was the void chest but since they are in the same dimension i can teleport the players that lost their stuff there
i was the only one using it as a full base but at least it wasant lost completely

**Comment by DavidM1A2** [comment]
For now, avoid going through the end portal. The bug will make it so your progress will wipe every time you do. I'll try to get a fix out tomorrow, since this is a massive issue.

 I don't have the most time to work on the mod anymore due to work, but I try to keep the mod working at least. 😊

**Comment by DavidM1A2** [comment]
Issue should be patched in https://www.curseforge.com/minecraft/mc-mods/afraid-of-the-dark/files/3789244

:)
