### ISSUE TITLE
Reduce texture resolution to match vanilla MC

### ISSUE THREAD

**Issue by DavidM1A2** [DavidM1A2/AfraidOfTheDark#3]
Many of the textures for blocks/entities/items in Afraid of the Dark are 64x64 or greater. Many players have complained that these textures are reducing FPS or don't match the vanilla feel, so they should be redone to fit the MC theme better in 16x16.

**Comment by LEWeee** [comment]
I have a few experiences with art (even though not so much with pixel art), I'll see what I can do.

**Comment by DavidM1A2** [comment]
I have a friend of mine working on a bunch of the textures, but if you have an idea for a texture you're welcome to give it a shot!

**Comment by DavidM1A2** [comment]
Done in v1.1.0
