### ISSUE TITLE
1.2.0 is incompatible with thermal expansion

### ISSUE THREAD

**Issue by lag42** [DavidM1A2/AfraidOfTheDark#8]
crash log [here](https://gist.github.com/lag42/0c3202e4953166daa1e4d768f179f6e7)
only afraid of the dark, thermal expansion and it's dependencies are present

**Comment by DavidM1A2** [comment]
This should be a quick fix, I'll have it out today or tomorrow.

**Comment by DavidM1A2** [comment]
Fixed, download available here: https://www.curseforge.com/minecraft/mc-mods/afraid-of-the-dark/files/2889102
