### ISSUE TITLE
[1.12.2] Format errors on Igneous Sword + Star Metal Khopesh

### ISSUE THREAD

**Issue by WolfBV** [DavidM1A2/AfraidOfTheDark#9]
![Screen Shot 2020-08-08 at 11 45 55 PM](https://user-images.githubusercontent.com/47493126/89741156-cd490480-da43-11ea-8206-77db416b0783.png)
![Screen Shot 2020-08-09 at 12 13 34 AM](https://user-images.githubusercontent.com/47493126/89741157-d0dc8b80-da43-11ea-95c8-2a25c10ef9ff.png)

**Comment by DavidM1A2** [comment]
Interesting, are you seeing this in NEI only or also when holding it in your hand?

**Comment by WolfBV** [comment]
Both with and without JEI installed, in hand and in the creative inventory. Not sure whether or not both of these items not appearing in the Vanilla Afraid of the Dark creative tab matters.

**Comment by DavidM1A2** [comment]
Fixed this in the latest version.
